apiVersion: v1
kind: Pod
metadata:
  name: webapp 
  labels:
    app: webapp
    releaase: '0'

spec:
  containers:
  - name: webapp-container
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0


---
# documenta separator

apiVersion: v1
kind: Pod
metadata:
  name: webappv1
  labels:
    app: webapp
    releaase: '1'

spec:
  containers:
  - name: webapp-container
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5


