apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  # make it uniq in the cluster

spec:
  selector:
    app: queue
    
  ports:
    - protocol: TCP
      port: 8161
      targetPort: 80
    
      nodePort: 30010
  type: NodePort
