apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  # make it uniq in the cluster

spec:
  selector:
    app: queue
    releaase: '1'
  ports:
    - name: http
      protocol: TCP
      port: 8161
      nodePort: 30010

    - name: endpoint
      protocol: TCP
      port: 61616
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  # make it uniq in the cluster

spec:
  selector:
    app: position
    releaase: '1'
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30020
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  # make it uniq in the cluster

spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8081
      nodePort: 30030
  type: NodePort